[package]
name = "pi-ish"
version = "0.1.0"
authors = ["Jacob Wahlgren <jacob.wahlgren@gmail.com>"]
description = "Estimate Ï€ using Monte Carlo simulation."

[dependencies]
rand = "0.3"
num_cpus = "1.0"
clap = "2.0"
